### PR TITLE
Share Listing

### PR DESCRIPTION
**Pull request by preetjdp**
# What This PR does.
Fixes https://github.com/covid-maps/covid-maps/issues/105

# Quirks with this approach
* The Listing did not have a inherit unique ID, thus using the placesID as the uniqueID.
* With the move to Postgres (https://github.com/covid-maps/covid-maps/pull/114), using the Postgres unique ID would be a better choice.
* Takes a bit of time to load, this is because fetches all the listings docs, then finds the one listing with a matching `placeId`, this will become slower with time.
* Results don't show up if the place is more than 5000KM's away from you.
This is in regards to =>
https://github.com/covid-maps/covid-maps/blob/25efc27c3800b1b4100f5e973bf1ed2f1e4fb943/src/MapWithSearch/Input/index.js#L87

### CODE REVIEW

**Comment by asanjeevrao** [comment]
@preetjdp this looks great. A few comments - 

1) Opening a Bangalore shared location in Vancouver shows Vancouver listings on a Bangalore map
WhatsApp Image 2020-04-07 at 12 52 05

2) Clicking on share button also activates card click action (moving card to top of listing) - these two actions should be decoupled

**Comment by asanjeevrao** [comment]
3) Update copy 

Check out the latest information on <store name> using Covid Maps — crowdsourced updates on essential services during lockdown period. <URL>

**Comment by preetjdp** [comment]
@asanjeevrao 
Have updated the message to reflect what you shared.

The bug where on clicking the share button the listing comes on top is rectified.

About the location bug (where you get a link for a location in Bangalore while you're in Vancouver) not able to filter out the results coming from that api, to accommodate for that.

Could use some help there.

And about the shortened url, most of the url shortening services are paid.
In terms of a simpler url, this is the only unique filed in the listing I could use right now.

Maybe If there would be the unique ID, the url would be much simpler.

**Comment by arjun27** [comment]
Yes! That’s a great and we can do this since we have unique server generated identifiers for stores. I’ll test and review your PR tomorrow :)

**Comment by arjun27** [comment]
@preetjdp - can you rebase this on top of master and use the store_id that is exposed in #186? Thanks!

**Comment by arjun27** [comment]
awesome work @preetjdp!!

**Pull request merged**
