### PR TITLE
Persist last selected address in session storage

### PR DESCRIPTION
**Pull request by Siddharth11**
Related: #66 

Demo
persist

### CODE REVIEW

**Comment by Siddharth11** [comment]
@arjun27 i've replaced `localStorage` with `sessionStorage` as per your suggestion

**Comment by asanjeevrao** [comment]
@arjun27 - 
1) when customers come back to the website after a while (say 1 hour), we should reset to current location I'm thinking? it's likely not the same use case and doesn't make sense to keep you on the same location 
2) even if the map is retained, should we keep search field filled? feels a little weird when you refresh the page and still see the search entry persisting 
3) experience is breaking when you use locate me. To repro - search for Indiranagar, then hit locate me, then go to Add a Store, then go back to Home Page
4) Meta question - should we be storing your search result or your map context? say you search for Indiranagar, then move the map, zoom in, 'Add a Store' and then come back to home page, ideal experience would be to go back to the same map view and not Indiranagar search view

**Comment by arjun27** [comment]
good feedback. After playing with this, I felt like the state should only persist while the app is used. I would prefer going back to the current location even after closing the tab (not just 1 hour)

**Comment by Siddharth11** [comment]
@arjun27 @asanjeevrao should i disable this for now then ?

**Comment by arjun27** [comment]
I don’t think we should disable it. Thinking we can just move to AppContext state and check the bugs that Sanjeev ran into (I haven’t looked into them but can pick them up later today if you’re busy)

**Comment by asanjeevrao** [comment]
agree - it still works all right for the most part. the only one that's a bug is #3 and it's not a big one.

**Pull request merged**
