### PR TITLE
Fixed dismiss card's bug

### LINKED ISSUE #289: New location card showing up again after dismissing
To reproduce search for a store that doesn't have a listing. Dismiss the new store card. Go to a different page and come back to home page, the blue card appears again. 

https://www.loom.com/share/e65c206b33e4455dbeb8f456c8acb470

### PR DESCRIPTION
**Pull request by xsihe**
Fixes #289 
What it should do now is that a dismissed card will stay dismissed for as long as:
- the user doesn't close the tab
- the user doesn't search for the same new location again 
- the user doesn't search for a different new location (in this case, there's just going to be a card for this location instead)

### CODE REVIEW

**Comment by Siddharth11** [comment]
> - the user doesn't search for the same new location again

@xsihe this seems incorrect. I think we can simplify this solution a lot. How about we keep the original logic, and just keep the default value of state var `showMissing` to `false`. And only set it to `true` inside `onSearchCompleted` method:

```javascript
  onSearchCompleted = result => {
    if (result && result.latLng) {
      this.setState(
        {
          searchResultLatlng: result.latLng,
          searchResult: result,
          isLoading: true,
          showMissing: isMissingLocationInformation(result),
        },
        () => {
          this.fetchResults();
        }
      );
    }
  };
```

this way we can remove the logic inside the `render` method to always display that block

**Comment by xsihe** [comment]
@Siddharth11 Incorrect in what way? Maybe I misunderstood it yesterday, but I thought the card was supposed to pop back up if the user ever decides to search for the same unregistered location again. 

I just tested your suggested solution, but it doesn't seem to resolve the issue where the blue card should stay dismissed when switching pages. When searching for a registered location, there'd also be the bug where the card would appear shortly while the results are loading and only disappear once the results are loaded. 

I'm also not sure how you'd like to take out the logic in render(), unless if I redo the logic for the creation of missing block altogether?

**Comment by Siddharth11** [comment]
> @Siddharth11 Incorrect in what way? Maybe I misunderstood it yesterday, but I thought the card was supposed to pop back up if the user ever decides to search for the same unregistered location again.

Yeah, my bad. It's correct. But the solution can be much simpler though. We don't need to use session storage here, it can complicate other scenarios. Ideally when you're using react, you should try to store as many variable in the component state (or maybe its parent state). We use session or local storage only if we want to persist some information for a longer time. And when you're React, session storage is essentially useless. Since it's a single page app, you have the ability to persist the session information in component state. Storing variables in component state is also better in a way that you can listen to variable changes, which won't happen with session storage. Your content inside render won't update just because you've updated something in session storage

<br />
<br />

> I'm also not sure how you'd like to take out the logic in render(), unless if I redo the logic for the creation of missing block altogether?

Inside render, try changing your current line 346 to this

```javascript
if (this.state.showMissing) {
```

**Comment by Siddharth11** [comment]
@xsihe let me test this with session storage for now. We can merge this and make improvements over it

**Comment by Siddharth11** [comment]
So, apparently `onSearchCompleted` runs more frequently than i expected and my proposed solution will require little more changes which are already part of other ticket. Your code is working as expected so I'll merge these changes 👍

**Pull request merged**
